### ISSUE TITLE
Refine `ci.yml` so that it is (even more) `glazier` specific.

### ISSUE THREAD

**Issue by bzm3r** [linebender/glazier#1]
I best-guess-ported over CI from `druid`, so someone should have a look at it once over in order to remove any tests that are unnecessary for `glazier`.

**Comment by jplatte** [comment]
The wayland and gtk backends are commented out, and gtk isn't currently being compiled. Those should probably be added back?

**Comment by waywardmonkeys** [comment]
I think this can be closed now. @xStrom, what do you think?

**Comment by xStrom** [comment]
I plan to do another pass on the CI real soon (this week) to integrate some lessons from `druid-shell` that happened post-fork.
