### ISSUE TITLE
Re-introduce font loading into Windows backend 

### ISSUE THREAD

**Issue by bzm3r** [linebender/glazier#10]
Used to come in from piet_common: https://github.com/linebender/glazier/blob/673d69bfe995db08809761c59490d49c687bd136/src/backend/windows/application.rs#L38

And was part of the `Application` struct: https://github.com/linebender/glazier/blob/673d69bfe995db08809761c59490d49c687bd136/src/backend/windows/application.rs#L51

**Comment by raphlinus** [comment]
I think font loading is out of scope of glazier. There's an *optional* piece of work of getting piet working on top of glazier, for which this would be relevant, but we're not committing to it yet.

Note (just for reference), IME integration is *in* scope, though it also involves fonts and rich text.
