### ISSUE TITLE
Investigate splitting gtk-rs dependency

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/glazier#101]
(Not sure if this is still up to date. Will need to investigate further.)

The gtk-rs crate takes a huge chunk of Glazier, Druid and Masonry's build times, but these crates only use a small fraction of the features offered by gtk. It might be feasible to cut out most of the unneeded features and get a much leaner dependency for shorter build times.

**Comment by waywardmonkeys** [comment]
GTK+ backend is gone, so no need to split it away.
