### ISSUE TITLE
OS Windows. linkage failed: unresolved external symbol error

### ISSUE THREAD

**Issue by Sol-Ell** [linebender/glazier#156]
### Error:
![Linkage error](https://github.com/linebender/glazier/assets/62467472/7a9636f2-b481-4e00-b613-a2606710a5ca)

### How did I get the error.
I recently moved from Linux to Windows and installed rust with msvc toolchain, added glazier as dependency. 
My code: 
```rust
use glazier::Application;

fn main() {
    Application::new()
        .unwrap()
        .run(None);
}
``` 

### Solution
As it turned out, there was an error in the "[SHCreateItemFromParsingName](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-shcreateitemfromparsingname)" function, which is located in the [Shell32 ](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-shcreateitemfromparsingname#:~:text=DLL-,Shell32.dll,-Feedback)library.
To fix this, just add 
```rust
#[cfg(target_os = "windows")]
fn main() {
    println!("cargo:rustc-link-lib=Shell32");
}
``` 
into "_build.rs_".

**Comment by waywardmonkeys** [comment]
PR #157 should fix this. My apologies for breaking it.

**Comment by Sol-Ell** [comment]
Thanks

**Comment by golanguage** [comment]
Have this issue been fixed?
I have pull the newest code, but on my pc without this build.rs link.exe cannot work.

**Comment by Sol-Ell** [comment]
In my case the problem was solved. Could you provide more information about the error and if possible steps to reproduce it?

**Comment by waywardmonkeys** [comment]
@golanguage It should be fixed on `main` now ... make sure you pulled and got everything. I also had tested it myself when I wrote the patch last night.

As @Sol-Ell said, please provide more info and an example of what you're doing and we'll take a look!

**Comment by golanguage** [comment]
> @golanguage It should be fixed on `main` now ... make sure you pulled and got everything. I also had tested it myself when I wrote the patch last night.
> 
> As @Sol-Ell said, please provide more info and an example of what you're doing and we'll take a look!

@waywardmonkeys 
Now is OK. 
May github pulling make some strange. I dont know .....

**Comment by waywardmonkeys** [comment]
No problem, great to hear that it is working for you now.
