### ISSUE TITLE
What to do with presentation strategy logic?

### ISSUE THREAD

**Issue by bzm3r** [linebender/glazier#18]
I am working on silencing some clippy lints, which is pointing me to consider what is happening with regards to presentation strategy in druid-shell:

https://github.com/linebender/glazier/blob/15306d13e229b29d82195bb05b787f0d71da412d/src/backend/windows/window.rs#L741

compared to in `unpiet`, where presentation strategy logic goes out the window:

https://github.com/linebender/glazier/blob/03691e73f5cde398b65162fe0aaea4dd31eab3f5/src/backend/windows/window.rs#L689

Tracing various threads back, I am lead to the blocker being [`create_dxgi_state`](https://github.com/linebender/glazier/blob/15306d13e229b29d82195bb05b787f0d71da412d/src/backend/windows/window.rs#L1663), particularly the creation of a `D3D11Device`, [as explained by Raph here](https://github.com/linebender/glazier/issues/9#issuecomment-1278422717).

Which leads me to wonder: does the presentation strategy logic also not belong in `glazier`? That seems to clash with my understanding of the purpose of glazier, so I'm wondering if I can have some insight.

**Comment by raphlinus** [comment]
The presentation logic probably doesn't belong in glazier now, but it should likely be revisited when we tackle how to integrate frame pacing (and window resize, which really isn't a problem any Windows GPU integration designed in the last 5 years even attempts to tackle).
