### ISSUE TITLE
Fresh checkout of glazier main branch doesn't build

### ISSUE THREAD

**Issue by mwcampbell** [linebender/glazier#39]
glazier's dependency on piet-gpu-hal refers to the dev branch of the piet-gpu repo, which apparently no longer exists, so I can't build from a fresh checkout of glazier.

**Comment by raphlinus** [comment]
I am not easily able to repro this, so lack confidence in a proposed fix (likely stale cache issues, as this should fail). Probably the best short term fix is to change the pin from "dev" to something like "1f9a4d53223fff150114f04f1b00d407790b5c30". A longer term fix is to change the example to wgpu-based.

**Comment by jneem** [comment]
I think this is fixed by #43. Please re-open if not.
