### ISSUE TITLE
Setup branch protection rules for `main`?

### ISSUE THREAD

**Issue by bzm3r** [linebender/glazier#4]

**Comment by derekdreery** [comment]
We should also set up the peer review workflow for approving PRs (same as for druid etc.)

**Comment by derekdreery** [comment]
I found myself with the permissions to enable branch protection for main, which I duly did. I was minimal - I disabled history rewrite and deletion but not the review process in case anyone is hacking atm and expecting it to be easy to push to. As long as history is preserved then we can always revert if there are any issues.

**Comment by jneem** [comment]
I just had a look, and it seems like reviews are required now so I'll close this.
