### ISSUE TITLE
Readme doesn't mention xkb dependency

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/glazier#46]
Right now when I compile glazier, I get this error:

```sh
Package xkbcommon-x11 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `xkbcommon-x11.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'xkbcommon-x11' found
  ', build.rs:20:36
```

I can roughly guess what I need to do, but I feel like you shouldn't get a build error because of a missing dependency if the README doesn't mention you have to install that dependency.

**Comment by derekdreery** [comment]
Yep sounds reasonable.
