### ISSUE TITLE
Glazier fails to compile with `--no-default-features --features="gtk"` on Linux

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/glazier#47]
I can't tell if that's deliberate. I assume it isn't.

I think `cargo build --features="gtk"` works fine, but then I end up depending on the x11 backed even though I don't use it.

**Comment by wusyong** [comment]
Adding `gtk` feature will still use `x11` bakcend. The error messages point that `piet` is not imported.
Should this crate import it to fix the error in web and gtk backend?
I'm glad to help if this is the way to fix it.
