### ISSUE TITLE
paint is never called on Wayland

### ISSUE THREAD

**Issue by rosefromthedead** [linebender/glazier#67]
In the shello example, the window that opens takes up the whole screen and "looks transparent" (which might just be kwin not painting *anything*, rather than painting full transparency). The window still receives clicks and keyboard events. `render()` never gets called.

**Comment by derekdreery** [comment]
Yep Wayland seems to be broken at the minute. I know that `winit` works reasonably well, so perhaps that would be a good start point. I would like to work on this but need to wait until I have some free time.

**Comment by DJMcNab** [comment]
Since #107, this is now resolved.
Although the actual backend still needs a lot of work - see #118
