### ISSUE TITLE
Input events are not correctly filtered on the X11 backend

### ISSUE THREAD

**Issue by CoffeeImpliesCode** [linebender/glazier#73]
When playing around with Xilem, I found that event handlers are triggered twice. E.g. in the button example bin, the counter is incremened twice per click.
After some suggestions on Zulip, I cloned glazier and debug-printed all input events, and they are duplicated in the following form (one click):
```
XinputButtonPress(ButtonPressEvent { response_type: 35, extension: 131, sequence: 650, length: 22, event_type: 4, deviceid: 11, time: 309212286, detail: 1, root: 475, event: 142606366, child: 0, root_x: 36498396, root_y: 40442140, event_x: 33221596, event_y: 32643356, sourceid: 11, flags: 0, mods: ModifierInfo { base: 0, latched: 0, locked: 0, effective: 0 }, group: GroupInfo { base: 0, latched: 0, locked: 0, effective: 0 }, button_mask: [0, 0, 0, 0, 0, 0, 0, 0], valuator_mask: [0, 0], axisvalues: [] })
XinputButtonPress(ButtonPressEvent { response_type: 35, extension: 131, sequence: 650, length: 22, event_type: 4, deviceid: 2, time: 309212286, detail: 1, root: 475, event: 142606366, child: 0, root_x: 36498396, root_y: 40442140, event_x: 33221596, event_y: 32643356, sourceid: 11, flags: 0, mods: ModifierInfo { base: 0, latched: 0, locked: 0, effective: 0 }, group: GroupInfo { base: 0, latched: 0, locked: 0, effective: 0 }, button_mask: [0, 0, 0, 0, 0, 0, 0, 0], valuator_mask: [0, 0], axisvalues: [] })
XinputButtonRelease(ButtonPressEvent { response_type: 35, extension: 131, sequence: 650, length: 22, event_type: 5, deviceid: 11, time: 309212403, detail: 1, root: 475, event: 142606366, child: 0, root_x: 36498396, root_y: 40442140, event_x: 33221596, event_y: 32643356, sourceid: 11, flags: 0, mods: ModifierInfo { base: 0, latched: 0, locked: 0, effective: 0 }, group: GroupInfo { base: 0, latched: 0, locked: 0, effective: 0 }, button_mask: [2, 0, 0, 0, 0, 0, 0, 0], valuator_mask: [0, 0], axisvalues: [] })
XinputButtonRelease(ButtonPressEvent { response_type: 35, extension: 131, sequence: 650, length: 22, event_type: 5, deviceid: 2, time: 309212403, detail: 1, root: 475, event: 142606366, child: 0, root_x: 36498396, root_y: 40442140, event_x: 33221596, event_y: 32643356, sourceid: 11, flags: 0, mods: ModifierInfo { base: 0, latched: 0, locked: 0, effective: 0 }, group: GroupInfo { base: 0, latched: 0, locked: 0, effective: 0 }, button_mask: [2, 0, 0, 0, 0, 0, 0, 0], valuator_mask: [0, 0], axisvalues: [] })
```
Note how they only differ in the deviceid field, being sent from devices 2 and 11. According to xinput, device 2 is a Virtual Core Pointer (master pointer) and device 11 is my actual mouse (slave pointer). Running xev, it does not show duplicate events, so it shouldn't be my configuration but insufficient control logic from glazier.

For reference, my system setup is the following
```
OS: Manjaro Linux x86_64
Host: 81SX Legion Y540-15IRH
Kernel: 5.15.94-1-MANJARO
Uptime: 5 days, 22 hours, 56 mins
Packages: 2904 (pacman), 7 (snap)
Shell: fish 3.6.0
Resolution: 1920x1080, 1920x1080
DE: GNOME 43.3
WM: Mutter
WM Theme: Adwaita
Theme: Adw-dark [GTK2/3]
Icons: Papirus-Dark-Maia [GTK2/3]
Terminal: alacritty
CPU: Intel i7-9750H (12) @ 4.500GHz
GPU: NVIDIA GeForce GTX 1660 Ti Mobile
Memory: 24277MiB / 32021MiB
```
and I am running X11, a backtrace also shows that the x11 backend is used.
I am using the main branch of Xilem and these issues happen both with its selected glazier version as well as a manually cloned main branch version of glazier (I did not check if those are different or the same).

How to reproduce:
* Run the Xilem button demo on an X11 linux desktop
* The counter should increment by 2 with each click

**Comment by jneem** [comment]
Thanks for the report! I'm not 100% sure what the best behavior is, but maybe it makes sense just to ignore the master events for now? Once PointerEvents are in, we could use the master/slave hierarchy to help us decide whether a pointer is the "main" poitner.

**Comment by jneem** [comment]
Eventually I think we do want to differentiate input devices (when we do PointerEvents), but sure, in the meantime I guess it makes more sense to use the master devices.
