### ISSUE TITLE
Figure out how to do text hit testing without piet

### ISSUE THREAD

**Issue by bzm3r** [linebender/glazier#8]
See: 

https://github.com/linebender/glazier/blob/d5f376dd469b21dfeec8b87d4c6b06ca75e0794e/src/text.rs#L421

https://github.com/linebender/glazier/blob/7ff78a8135c386a422d5ac85afd7f4d114cf320a/src/backend/mac/text_input.rs#L220

**Comment by raphlinus** [comment]
I took a quick look at this. I think the main sticking point is the [HitTestPoint](https://docs.rs/piet/latest/piet/struct.HitTestPoint.html) which is quite simple - it's just an offset and a boolean. So here the IME integration happens to require a piet type, but I don't believe it has a hard dependency on piet itself to represent the text being hit-tested. I believe a solution is to duplicate this struct inside glazier, but haven't validated this yet.
