### ISSUE TITLE
MouseButton variants should be named Primary/Secondary instead of Left/Right/Middle

### ISSUE THREAD

**Issue by lord** [linebender/glazier#88]
TimTom on Zulip points out that the official spec doesn't say Left/Right because some users swap their primary mouse button; we should probably change these variant names to match [the spec](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons).

**Comment by derekdreery** [comment]
This sounds good to me, but we should discuss at the Office hours.

**Comment by jneem** [comment]
I'm fine with discussing this in office hours, but I think that in general
we should make decisions here on the GitHub issues: there's a better record
of discussion, and the async format might be easier for some people.

**Comment by jneem** [comment]
Discussed in office hours, and everyone was fine with the renaming. :heavy_check_mark:
